os: bionic

language: cpp

git:
  clone: false
  submodules: false

services:
  - docker

before_install:
  - docker pull brettviren/wct-testing

script:
  - docker run brettviren/wct-testing ./run.sh


